feat: handle hook module enable/disable actions

diff --git a/bash-hooks b/bash-hooks
--- a/bash-hooks
+++ b/bash-hooks
@@ -62,6 +62,7 @@ SOURCE_PULL_PACKAGE=""
 
 DISABLE_HOOK_STATUS=-1
 DISABLE_HOOK=false
+HOOKS_TO_UPDATE=()
 
 # -------------- #
 # MISC FUNCTIONS #
@@ -165,9 +166,19 @@ for ARG in "$@"; do
     --enable | -e)
       DISABLE_HOOK_STATUS=0
       ;;
+    --enable=* | -e=*)
+        DISABLE_HOOK_STATUS=0
+        IFS=',' read -ra BLOCKS <<< "${ARG#*=}"
+        HOOKS_TO_UPDATE+=("${BLOCKS[@]}")
+        ;;
     --disable | -d)
       DISABLE_HOOK_STATUS=1
       ;;
+    --disable=* | -d=*)
+        DISABLE_HOOK_STATUS=1
+        IFS=',' read -ra BLOCKS <<< "${ARG#*=}"
+        HOOKS_TO_UPDATE+=("${BLOCKS[@]}")
+        ;;
     --help | -h)
       print_help
       exit 0
@@ -181,6 +192,15 @@ OUTPUT_FILE="${WORKSPACE}/${OUTPUT_FILE}"
 # --------- #
 # FUNCTIONS #
 # --------- #
+
+format_hook_name() {
+    local SCRIPT_ID="$1"
+
+    SCRIPT_ID="${SCRIPT_ID^^}"
+    SCRIPT_ID="${SCRIPT_ID//-/_}"
+
+    echo "HOOK_${SCRIPT_ID}"
+}
 
 update_hook_variable() {
     local HOOK_NAME=$1
@@ -222,6 +242,35 @@ update_global_hook_state() {
     fi
 }
 
+update_single_hook_state() {
+     for HOOK_ID in "${HOOKS_TO_UPDATE[@]}"; do
+        local HOOK_NAME
+        local NEW_STATE
+
+        HOOK_NAME=$(format_hook_name "$HOOK_ID")
+        NEW_STATE=$([[ "$DISABLE_HOOK_STATUS" -eq 0 ]] && echo true || echo false)
+
+        if ! update_hook_variable "$HOOK_NAME" "$NEW_STATE"; then
+            echo -e "${RED}Failed to update hook '${HOOK_ID}'.${RESET}"
+            return 1
+        fi
+
+        if [[ "${NEW_STATE}" == true ]]; then
+            echo -e "${YELLOW}The hook '${HOOK_ID}' has been enabled.${RESET}"
+        else
+            echo -e "${YELLOW}The hook '${HOOK_ID}' has been disabled.${RESET}"
+        fi
+    done
+}
+
+update_hooks_state() {
+    if (( ${#HOOKS_TO_UPDATE[@]} > 0 )); then
+        update_single_hook_state
+    else
+        update_global_hook_state
+    fi
+}
+
 format_package_name() {
     local PACKAGE="$1"
     
@@ -236,13 +285,15 @@ format_package_name() {
 }
 
 log_script_execution() {
-    local SCRIPT=$1
-    local EXPECT=$2
-    local RETURN=$3
-    local ARGS=$4
-    local FLAGS=$5
-    local IS_REMOTE=$6
+    local SCRIPT_ID=$1
+    local SCRIPT=$2
+    local EXPECT=$3
+    local RETURN=$4
+    local ARGS=$5
+    local FLAGS=$6
+    local IS_REMOTE=$7
 
+    local HOOK_NAME
     local LOG_DIRECTION="ne"
     local LOG_RETURN=1
 
@@ -279,13 +330,19 @@ log_script_execution() {
         LOG_FLAGS=" $LOG_FLAGS"
     fi
 
+    HOOK_NAME=$(format_hook_name "$SCRIPT_ID")
+
     {
-        echo -e "\nprintf \"\${BOLD}\\\\nExecuting '${SCRIPT}' script...\${RESET}\\\\n\"" 
-        echo "$SCRIPT$ARGS$LOG_FLAGS"
-        echo "if [ \$? -${LOG_DIRECTION} 0 ]; then"
-        echo "    exit ${LOG_RETURN}"
-        echo 'fi'
-        echo -e "printf \"\${BOLD}\\\\n <-----------------> \\\\n\${RESET}\""
+        echo
+        echo -e "${HOOK_NAME}=true"
+        echo -e "if [ \"\${$HOOK_NAME}\" == true ]; then"
+        echo -e "  printf \"\${BOLD}\\\\nExecuting '${SCRIPT}' script...\${RESET}\\\\n\""
+        echo -e "  $SCRIPT$ARGS$LOG_FLAGS"
+        echo -e "  if [ \$? -${LOG_DIRECTION} 0 ]; then"
+        echo -e "      exit ${LOG_RETURN}"
+        echo -e "  fi"
+        echo -e "  printf \"\${BOLD}\\\\n <-----------------> \\\\n\${RESET}\""
+        echo -e "fi"
     } >> "$OUTPUT_FILE"
 }
 
@@ -446,7 +503,7 @@ load_remote_scripts() {
 
         fetch_write_remote_file "$PROJECT" "$FILE_URL" "$LOCATION" true
         
-        log_script_execution "$LOCATION" "$EXPECT" "$RETURN" "$ARGS" "$FLAGS" true
+        log_script_execution "$REPO_ID" "$LOCATION" "$EXPECT" "$RETURN" "$ARGS" "$FLAGS" true
 
         COUNT_REMOTE=$((COUNT_REMOTE + 1))
         if [ -n "$LIST_REMOTE" ]; then
@@ -569,7 +626,7 @@ load_local_scripts() {
 
         file_must_exists "$LOCATION"
 
-        log_script_execution "$SCRIPT" "$EXPECT" "$RETURN" "$ARGS" "$FLAGS" false
+        log_script_execution "$SCRIPT_ID" "$SCRIPT" "$EXPECT" "$RETURN" "$ARGS" "$FLAGS" false
 
         chmod +x "$LOCATION"
 
@@ -669,7 +726,7 @@ touch "$OUTPUT_FILE"
 # ----------- #
 
 if [[ "$DISABLE_HOOK_STATUS" != -1 ]]; then
-    update_global_hook_state
+    update_hooks_state
     exit 0
 fi
 
